api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    name_converter: serializer.name_converter.camel_case_to_snake_case
    path_segment_name_generator: api_platform.path_segment_name_generator.dash

    formats:
        jsonld:   ['application/ld+json']
        jsonapi:  ['application/vnd.api+json']
        json:     ['application/json']
        csv:      ['text/csv']
        html:     ['text/html']

    enable_swagger_ui: false
