version: '3'

services:
    php:
        build: .

        volumes:
            - ./var/jwt:/secrets/jwt
            - .:/srv/api:rw

        environment:
            DATABASE_URL: postgres://app:app_passwd@db/app

        depends_on:
            - db

    web:
        image: nginx:alpine

        volumes:
            - ./public:/srv/api/public:ro
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

        depends_on:
            - php
        ports:
            - 8080:80

    db:
        image: postgres:10-alpine

        volumes:
            - db-data:/var/lib/postgresql/data:rw

        ports:
            # expose the port 54320 to host if you need to connect to the db
            - 54320:5432

        environment:
            POSTGRES_USER: app
            POSTGRES_DB: app
            POSTGRES_PASSWORD: app_passwd

volumes:
    db-data: {}
